version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: yarn dev
    ports:
      - 3000:3000
    volumes:
      - ./app:/code
      - /code/node_modules

volumes:
  db:
