# Generated by Django 3.2.18 on 2023-04-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='order',
            field=models.IntegerField(),
        ),
    ]
